name: Copy Folder from Target Branch

on:
  push
jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Change working directory
        run: cd ${{ github.workspace }}

      - name: Configure Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Switch to target branch
        run: |
          git fetch origin
          git checkout main

      - name: Copy folder to source branche
        run: |
          git checkout fa-v2 
          git merge --no-commit fa-v2 test.txt
          git commit -m "Copied folder from target branch"
          git push