name: Copy Folder from Target Branch

on:
  pull_request

jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: change working dir
        run: cd $GITHUB_WORKSPACE

      - name: user sign in
        run: |
          git config user.email "actions@github.com"
          git config user.name "github actions"

      - name: Switch to target branch
        run: |
          git fetch origin
          git checkout ${{ github.event.pull_request.head.ref }}

      - name: Copy folder to head branch
        run: git checkout ${{ github.event.pull_request.base.ref }} && git merge --no-commit ${{ github.event.pull_request.head.ref }}:./copy && git commit -m "Copied folder from target branch" && git push